name = "LFT"
version = "0.1.0"
keywords = ["logic", "quantum", "foundations"]

[dependencies]
mathlib = { git = "https://github.com/leanprover-community/mathlib4.git", rev = "v4.21.0" }

[[lean_lib]]
name = "LFT"